spring.application.name=newsletter-api
server.port=8081

spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
jwt.secure-cookie=false

aws.s3.bucket=replace-me
aws.s3.region=

aws.ses.region=
